spring:
  application:
    name: service-registry

server:
  port: 9098


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# Zip-Kin
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9400/api/v2/spans