spring:
  application:
    name: shipping-service

server:
  port: 9092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl :
      defaultZone: http://localhost:9098/eureka/

