spring:
  application:
    name: order-service

server:
  port: 9091

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl :
      defaultZone: http://localhost:9098/eureka/