spring:
  application:
    name: order-service

server:
  port: 9091

# eureka server discovery
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl :
      defaultZone: http://localhost:9098/eureka/

# Zip-Kin
management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9400/api/v2/spans